import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { cn } from "@/lib/utils";
import React from "react";
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "sonner";

const cabinetGroteskFont = localFont({
  variable: "--cabinet-grotesk-font",
  display: "swap",
  src: [
    {
      path: "../fonts/CabinetGrotesk-Variable.ttf",
      weight: "variable",
    },
  ],
});

const satoshiFont = localFont({
  variable: "--satoshi-font",
  display: "swap",
  src: [
    {
      path: "../fonts/Satoshi-Variable.ttf",
      weight: "variable",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(cabinetGroteskFont.className, satoshiFont.className)}>
        <ThemeProvider attribute="class" defaultTheme="light">
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
