import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { cn } from "@/lib/utils";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import React from "react";

const cabinetGroteskFont = localFont({
  variable: "--cabinet-grotesk-font",
  display: "swap",
  src: [
    {
      path: "../fonts/CabinetGrotesk-Variable.ttf",
      weight: "variable",
    },
  ],
});

const satoshiFont = localFont({
  variable: "--satoshi-font",
  display: "swap",
  src: [
    {
      path: "../fonts/Satoshi-Variable.ttf",
      weight: "variable",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body
          className={cn(cabinetGroteskFont.className, satoshiFont.className)}
        >
          <div className="flex h-screen">
            <Sidebar />
            <div className="flex flex-col flex-1">
              <Header />
              <main className="flex-1 p-8 bg-background overflow-y-auto">
                {children}
              </main>
            </div>
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
